### PR TITLE
fix QRibbon's decoration prop validator

### PR DESCRIPTION
**Pull request by lucasfernog**

### CODE REVIEW

**Comment by webnoob** [comment]
I'm torn with this ....
I discussed prop names with @hawkeye64 and couldn't decide between `round` or `rounded`. I went with `rounded` because it implies one edge is round as opposed to the whole thing ...

**Comment by lucasfernog** [comment]
Whatever you decide, it must be the same between .styl files and prop validation rule... but that choice is tricky 🤔

**Comment by webnoob** [comment]
As it stands, it's consistent.
I've put a post on discord about it.
Let people who use it decide, I'm not precious about it :)

**Comment by webnoob** [comment]
Oh, wait.... I thought it was called rounded .... ! It's `round`.
Yes, this needs to be consistent 🤦‍♂

**Comment by webnoob** [comment]
I've got a bigish commit coming in so I've changed this locally as all the examples will need changing as well which your PR doesn't do.

**Comment by lucasfernog** [comment]
Well I thought only the validation was wrong, the code/docs I looked named it as "rounded" but not the prop validation, but ok

**Comment by webnoob** [comment]
> Well I thought only the validation was wrong, the code/docs I looked named it as "rounded" but not the prop validation, but ok

I'll get my head screwed on straight at some point. You're right.
Sorry mate, juggling loads of other jobs 🙄

**Pull request merged**
