### PR TITLE
feat(github): Adding githib history mode hacks and others (see desc)

### PR DESCRIPTION
**Pull request by hawkeye64**
Also renamed path '/' to '/docs', updated '/' to redirect to '/docs'. This keeps your router links from having duplicity.
Added script "lint-fix" - call `yarn lint-fix` to automatically have lint fix things.
Added build script "build-demo" - call `yarn build-demo` to generate build for docs folder. Put results into github and have github settings to use 'docs' folder for docs.

### CODE REVIEW

**Comment by hawkeye64** [comment]
Make sure anytime you want to publish docs, you run `yarn build-demo` and push results to github. Docs website will be updated in 2-5 minutes.

**Comment by hawkeye64** [comment]
And, I changed your "Fork me on github" to point to your repo.

**Comment by hawkeye64** [comment]
And, I added eslint to your QRibbon project

**Comment by webnoob** [comment]
> Make sure anytime you want to publish docs, you run `yarn build-demo` and push results to github. Docs website will be updated in 2-5 minutes.

I've been manually copy / pasting over to my `webnoob.gitbub.io` repo and committing / pushing. Are you saying that won't be required now?

**Pull request merged**
